# Generated by Django 4.2.16 on 2024-12-16 17:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_empresa', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='profile_pics/user2.jpg', upload_to='profile_pics/')),
                ('is_first_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id_cardapio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapio_images/')),
                ('ativo', models.BooleanField(default=False)),
                ('borda_recheada', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length='100')),
                ('telefone', models.TextField(max_length='16')),
                ('cpf', models.TextField(max_length='14')),
                ('dataN', models.DateField()),
                ('genero', models.TextField(max_length='20', null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.TextField(max_length='18', unique=True)),
                ('razao', models.TextField(max_length='100')),
                ('nome_fantasia', models.TextField(max_length='100')),
                ('data_abertura', models.DateField()),
                ('subdominio', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('logo', models.ImageField(default='logo_pics/logo_default.png', upload_to='logo_pics/')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='empresa_banners/')),
                ('tempo_entrega_min', models.IntegerField(blank=True, null=True)),
                ('tempo_entrega_max', models.IntegerField(blank=True, null=True)),
                ('preco_frete', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('pedido_minimo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('perfil_empresa', models.ImageField(default='profile_pics/user2.jpg', upload_to='profile_pics/')),
                ('itens_destaque', models.ManyToManyField(blank=True, related_name='em_destaque', to='authentication.cardapio')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('unidade', 'Unidade'), ('litro', 'Litro')], default='kg', max_length=50)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='authentication.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atual', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='pendente', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_pedido', models.IntegerField(unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendente_movi_estoque', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_estoque', to='authentication.empresa')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cardapio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cardapio')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='authentication.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteCardapio',
            fields=[
                ('id_ingredientecardapio', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardapio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='authentication.cardapio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienteCardapio', to='authentication.empresa')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='authentication.empresa')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoEmpresa',
            fields=[
                ('id_enderecoempresa', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id_enderecocliente', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(choices=[('casa', 'Casa'), ('trabalho', 'Trabalho')], default='casa', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='authentication.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('Dono', 'Dono'), ('Caixa', 'Caixa'), ('Pizzaiolo', 'Pizzaiolo')], max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='pizzarias_favoritas',
            field=models.ManyToManyField(blank=True, related_name='clientes_favoritos', to='authentication.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='authentication.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.cliente'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='authentication.categoria'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='authentication.empresa'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_itempedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardapio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='authentication.pedido')),
            ],
            options={
                'unique_together': {('pedido', 'cardapio_item')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cardapio',
            unique_together={('empresa', 'nome')},
        ),
        migrations.CreateModel(
            name='AvaliacaoPedido',
            fields=[
                ('id_avaliacaopedido', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='authentication.pedido')),
            ],
            options={
                'unique_together': {('pedido',)},
            },
        ),
    ]
