# Generated by Django 4.2.16 on 2024-12-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_pedido_status_programafidelidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeviceSession',
        ),
    ]
