# Generated by Django 4.2.16 on 2024-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ingrediente_estoque_minimo_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.TextField(max_length='18', unique=True),
        ),
    ]
