# Generated by Django 4.2.16 on 2024-12-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_empresausuario_usuario_delete_devicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaopedido',
            name='resposta',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
