# Generated by Django 4.2.16 on 2025-01-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.TextField(max_length='14', unique=True),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='local',
            field=models.CharField(choices=[('casa', 'Casa'), ('trabalho', 'Trabalho'), ('outros', 'Outros')], default='casa', max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
