# Generated by Django 4.2.16 on 2025-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_avaliacaopedido_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='canal',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
