# Generated by Django 4.2.16 on 2024-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_categoria_alter_cardapio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
