# Generated by Django 4.2.16 on 2025-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_cliente_cpf_alter_enderecocliente_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
