# Generated by Django 4.2.16 on 2024-12-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_cardapio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='borda_recheada',
            field=models.BooleanField(default=False),
        ),
    ]
