# Generated by Django 4.2.16 on 2024-12-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_cardapio_borda_recheada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientecardapio',
            name='unidade',
        ),
        migrations.AddField(
            model_name='ingredientecardapio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
