# Generated by Django 4.2.16 on 2025-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_papel_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='papel_adm',
            field=models.CharField(choices=[('Master', 'Master'), ('Atendente', 'Atendente'), ('Gerente', 'Gerente')], default='Master', max_length=50),
        ),
    ]
