# Generated by Django 4.2.16 on 2025-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_papel_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_adm',
            field=models.BooleanField(default=False),
        ),
    ]
