# Generated by Django 4.2.16 on 2024-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_ingredientecardapio_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientecardapio',
            name='completo',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
