# Generated by Django 4.2.16 on 2025-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_papel_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresausuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='papel_adm',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Atendente', 'Atendente'), ('Gerente', 'Gerente')], max_length=50, null=True),
        ),
    ]
