# Generated by Django 4.2.16 on 2025-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_empresausuario_ativo_alter_customuser_papel_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
