# Generated by Django 4.2.16 on 2025-01-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.enderecocliente'),
            preserve_default=False,
        ),
    ]
