# Generated by Django 4.2.16 on 2025-01-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_pedido_endereco_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('vendas_mes_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lucro_mes_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendas_mes_passado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lucro_mes_passado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variacao_percentual_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
            ],
        ),
    ]
