# Generated by Django 4.2.16 on 2025-02-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_relatoriofinanceiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecopedido',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.enderecopedido'),
        ),
    ]
