# Generated by Django 4.2.16 on 2025-02-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_enderecocliente_latitude_enderecocliente_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoempresa',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='enderecoempresa',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='authentication.empresa'),
        ),
    ]
