# Generated by Django 4.2.16 on 2025-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_enderecoempresa_latitude_enderecoempresa_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoempresa',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='-23.6802082', max_digits=9),
        ),
        migrations.AlterField(
            model_name='enderecoempresa',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='-46.6919477', max_digits=9),
        ),
    ]
