# Generated by Django 4.2.16 on 2025-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_enderecocliente_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocliente',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
