# Generated by Django 4.2.16 on 2025-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_enderecocliente_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaopedido',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
